/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.valpha.greeting' plugin.
 */
class VulcanPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.valpha.vulcan")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
