/*
 * This source file was generated by the Gradle 'init' task
 */
package com.valpha

import java.io.File
import kotlin.test.assertTrue
import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.io.TempDir
import kotlin.contracts.contract
import kotlin.test.BeforeTest

/**
 * A simple functional test for the 'com.valpha.greeting' plugin.
 */
class VulcanPluginFunctionalTest {

    @field:TempDir
    lateinit var projectDir: File
//
//    private val buildFile by lazy { projectDir.resolve("build.gradle.kts") }
//    private val settingsFile by lazy { projectDir.resolve("settings.gradle") }

    @BeforeTest
    fun setup() {
        // Any setup before each test can be done here
        // copy resources to temp projectDir if needed
        val testProjectFile = javaClass.classLoader.getResource("testProject")?.toURI()?.let { File(it) }
            ?: error { "Test project resource not found" }
//        println("testProjectFile dir walk: ${testProjectFile.walk().joinToString("\n")}")
        testProjectFile.copyRecursively(projectDir, true)
    }

    @Test
    fun `can run task`() {

//        println("Project dir walk: ${projectDir.walk().joinToString("\n")}")

        // Run the build
        val runner = GradleRunner.create()
            .forwardOutput()
            .withDebug(true)
            .withPluginClasspath()
            .withArguments("greeting")
            .withProjectDir(projectDir)

        val result = runner.build()

        // Verify the result
        assertTrue(result.output.contains("Hello from plugin 'com.valpha.greeting'"))
    }
}
