import org.gradle.kotlin.dsl.invoke

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/9.2.0/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
//    `java-gradle-plugin`
    `kotlin-dsl`
    id("com.gradle.plugin-publish") version "2.0.0"

    // Apply the Kotlin JVM plugin to add support for Kotlin.
//    alias(libs.plugins.kotlin.jvm)
}

repositories {
    maven("https://mirrors.huaweicloud.com/repository/maven/")
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("2.0.0")
        }

    }
}

group = "io.github.valpha"
version = "1.0"

gradlePlugin {
    vcsUrl.set("https://github.com/Valpha/Vulcan-gradle-plugin")
    website.set("https://github.com/Valpha/Vulcan-gradle-plugin")
    val vulcan by plugins.creating {
        id = "io.github.valpha.vulcan"
        implementationClass = "io.github.valpha.VulcanPlugin"
        displayName = "Vulcan Gradle Plugin"
        description = "A Gradle plugin for Android project modularization and flavor management."
        tags = listOf("Android", "Vulcan", "modularization", "flavor", "clean architecture")
    }
}

publishing.repositories.maven {
    name = "local-test"
    url = uri("$projectDir/.repo")
}

dependencies {
    compileOnly("com.android.tools.build:gradle-api:8.13.0")
    implementation(gradleKotlinDsl())
}
