import org.gradle.kotlin.dsl.invoke

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/9.2.0/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `kotlin-dsl`
    id("com.gradle.plugin-publish") version "2.0.0"
}

repositories {
    maven("https://mirrors.huaweicloud.com/repository/maven/")
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("2.0.0")
        }

    }
}

group = "io.github.valpha.vulcan"
version = "1.0"
base.archivesName = "vulcan-plugin"

gradlePlugin {
    vcsUrl.set("https://github.com/Valpha/Vulcan-gradle-plugin")
    website.set("https://github.com/Valpha/Vulcan-gradle-plugin")
    val vulcan by plugins.creating {
        id = "io.github.valpha.vulcan"
        implementationClass = "io.github.valpha.VulcanPlugin"
        displayName = "Vulcan Gradle Plugin"
        description = "A Gradle plugin for Android project modularization and flavor management."
        tags = listOf("Android", "Vulcan", "modularization", "flavor", "clean architecture")
    }
}

publishing {
    publications {
        withType<MavenPublication> {
            this.artifactId = base.archivesName.get()
        }
    }
    repositories {
        maven {
            name = "local-test"
            url = uri("$projectDir/.repo")
        }
        maven {
            name = "bestune"
            url = uri("http://10.170.8.35:8077/api/v4/projects/311/packages/maven")
            credentials(HttpHeaderCredentials::class) {
                name = "Private-Token"
                value = findProperty("vulcanPublishToken") as String?
                isAllowInsecureProtocol = true
            }
            authentication {
                create("header", HttpHeaderAuthentication::class)
            }
        }
    }
}
dependencies {
    compileOnly("com.android.tools.build:gradle-api:8.13.0")
    implementation(gradleKotlinDsl())
}
