/*
 * This source file was generated by the Gradle 'init' task
 */
package com.valpha

import com.valpha.vulcan.model.VulcanConfig
import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.kotlin.dsl.create

/**
 * A simple 'hello world' plugin.
 */
class VulcanPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'com.valpha.greeting'")
            }
        }

        // My Logic Here
        with(project) {
            val vulcanExtension = extensions.create<VulcanConfig>("vulcan", project)
        }


    }
}
